-- Insert news items into market_news table
INSERT INTO market_news (
    title,
    source,
    url,
    published_at,
    sentiment_score,
    summary,
    entities,
    impact_level,
    category,
    market_impact_score,
    affected_sectors,
    time_horizon
) VALUES
(
    'RBI Keeps Repo Rate Unchanged at 6.5% for Seventh Consecutive Time',
    'Economic Times',
    'https://economictimes.indiatimes.com/rbi-repo-rate-decision',
    '2024-04-05T11:30:00Z',
    -0.3,
    'The Reserve Bank of India maintains status quo on key rates, citing persistent inflation concerns while maintaining growth forecast at 7% for FY25.',
    '["rbi", "monetary policy", "interest rates", "india"]',
    'Medium',
    'Policy',
    65,
    '["Banking", "Financial Services"]',
    'Short'
),
(
    'US Fed Signals Just One Rate Cut in 2024 Amid Sticky Inflation',
    'Bloomberg',
    'https://www.bloomberg.com/fed-rate-cut-2024',
    '2024-04-10T18:45:00Z',
    -1.2,
    'Federal Reserve projects only one interest rate cut this year as inflation remains above target, causing global market volatility.',
    '["federal reserve", "interest rates", "global markets", "inflation"]',
    'High',
    'Global Markets',
    85,
    '["Global Markets", "Financial Services"]',
    'Medium'
),
(
    'India''s GDP Growth Surprises at 8.4% in Q3 FY24',
    'MoneyControl',
    'https://www.moneycontrol.com/india-gdp-q3-fy24',
    '2024-04-12T05:15:00Z',
    1.5,
    'India''s economy grows faster than expected in December quarter, boosting government''s economic management credentials.',
    '["gdp", "economy", "india", "growth"]',
    'High',
    'Economy',
    90,
    '["All Sectors"]',
    'Medium'
),
(
    'Nvidia Shares Surge 10% After Stellar AI Chip Demand Forecast',
    'CNBC',
    'https://www.cnbc.com/nvidia-ai-chip-demand',
    '2024-04-15T20:30:00Z',
    2.0,
    'Chipmaker Nvidia sees record revenue projections driven by AI boom, lifting global tech stocks.',
    '["nvidia", "artificial intelligence", "technology", "global markets"]',
    'High',
    'Technology',
    95,
    '["Technology", "Semiconductors"]',
    'Short'
),
(
    'SEBI Proposes Stricter Rules for Algorithmic Trading in India',
    'Business Standard',
    'https://www.business-standard.com/sebi-algo-trading-rules',
    '2024-04-08T14:20:00Z',
    -0.8,
    'Market regulator seeks to implement new safeguards for algo trading after recent market volatility incidents.',
    '["sebi", "algorithmic trading", "regulation", "india"]',
    'Medium',
    'Regulation',
    70,
    '["Financial Services", "Technology"]',
    'Medium'
),
(
    'Oil Prices Hit 5-Month High Amid Middle East Tensions',
    'Reuters',
    'https://www.reuters.com/oil-price-surge',
    '2024-04-11T09:10:00Z',
    -1.5,
    'Brent crude crosses $90/barrel as geopolitical risks escalate, raising inflation concerns globally.',
    '["crude oil", "commodities", "inflation", "global markets"]',
    'High',
    'Commodities',
    80,
    '["Oil & Gas", "Transportation", "Manufacturing"]',
    'Short'
),
(
    'Tata Motors Announces $2 Billion EV Battery Plant in Gujarat',
    'Livemint',
    'https://www.livemint.com/tata-motors-ev-plant',
    '2024-04-09T11:45:00Z',
    1.2,
    'Automaker makes largest EV commitment in India to date, shares rise 5% on announcement.',
    '["tata motors", "electric vehicles", "automobile", "india"]',
    'High',
    'Corporate',
    85,
    '["Automobile", "Renewable Energy"]',
    'Long'
),
(
    'Japan''s Yen Hits 34-Year Low Against Dollar, Prompting Intervention Warnings',
    'Financial Times',
    'https://www.ft.com/yen-34-year-low',
    '2024-04-16T07:25:00Z',
    -0.7,
    'Japanese currency continues slide despite BOJ''s rate hike, creating ripple effects in Asian markets.',
    '["forex", "yen", "japan", "global markets"]',
    'Medium',
    'Global Markets',
    75,
    '["Financial Services", "Export-Oriented Industries"]',
    'Short'
),
(
    'Reliance Jio Announces 20% Hike in Tariffs Starting June',
    'ET Telecom',
    'https://telecom.economictimes.indiatimes.com/jio-tariff-hike',
    '2024-04-14T13:15:00Z',
    0.5,
    'India''s largest telecom operator raises prices across all plans, likely triggering industry-wide increases.',
    '["reliance jio", "telecom", "tariffs", "india"]',
    'Medium',
    'Corporate',
    60,
    '["Telecommunications"]',
    'Short'
),
(
    'Gold Prices Scale Record High Amid Safe-Haven Demand',
    'CNBC TV18',
    'https://www.cnbctv18.com/gold-price-record-high',
    '2024-04-17T10:05:00Z',
    0.3,
    'Global gold prices touch $2,400/oz as investors seek safety from geopolitical and inflation risks.',
    '["gold", "commodities", "safe haven", "global markets"]',
    'Medium',
    'Commodities',
    70,
    '["Precious Metals", "Jewelry"]',
    'Short'
); 